import { Box } from "@mui/material";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { useState, useMemo } from "react";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import ChatInput from "./components/ChatInput";

function App() {
  const [messages, setMessages] = useState([]);
  const [mode, setMode] = useState("light");

  const toggleTheme = () => {
    setMode((prev) => (prev === "light" ? "dark" : "light"));
  };

  const theme = useMemo(
  () =>
    createTheme({
      palette: {
        mode,
        ...(mode === "light"
          ? {
              primary: {
                main: "#e3e2e287", 
              },
              background: {
                default: "#f7f7f8", 
                paper: "#ffffff00",
              },
            }
          : {
              primary: {
                main: "#1b1818af", 
              },
              background: {
                default: "#0b0b0b", 
                paper: "#030303b4",
              },
            }),
      },
    }),
  [mode]
);

  const handleSend = (msg) => {
    const userMessage = { text: msg, type: "user" };
    setMessages((prev) => [...prev, userMessage]);

    setTimeout(() => {
      const assistantMessage = {
        text: "This is an autogenerated message. Welcome to ChatGPT.",
        type: "assistant",
      };
      setMessages((prev) => [...prev, assistantMessage]);
    }, 600);
  };

  return (
    <ThemeProvider theme={theme}>
      <Box
        sx={{
          display: "flex",
          height: "100vh",
          width: "100vw",
          bgcolor: "background.default",
          color: "text.primary",
        }}
      >
        <Sidebar toggleTheme={toggleTheme} />

        <Box
          sx={{
            flexGrow: 1,
            display: "flex",
            flexDirection: "column",
            minWidth: 0,
            overflow: "hidden",
          }}
        >
          <Header />

          {messages.length === 0 ? (
            <Box
              sx={{
                flexGrow: 1,
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                px: 2,
              }}
            >
              <Box sx={{ width: "100%", maxWidth: 800 }}>
                <ChatInput onSend={handleSend} />
              </Box>
            </Box>
          ) : (
            <>
              <Box
                sx={{
                  flexGrow: 1,
                  overflowY: "auto",
                  px: 2,
                }}
              >
                <Box
                  sx={{
                    width: "100%",
                    maxWidth: 800,
                    mx: "auto",
                    pt: 4,
                    pb: 2,
                  }}
                >
                  {messages.map((msg, idx) => (
                    <Box
                      key={idx}
                      sx={{
                        display: "flex",
                        justifyContent:
                          msg.type === "user"
                            ? "flex-end"
                            : "flex-start",
                        mb: 3,
                      }}
                    >
                      <Box
                        sx={{
                          bgcolor:
                            msg.type === "user"
                              ? "primary.main"
                              : "background.paper",
                          color:
                            msg.type === "user"
                              ? "primary.contrastText"
                              : "text.primary",
                          px: 3,
                          py: 1,
                          borderRadius: 8,
                          maxWidth: "75%",
                        }}
                      >
                        {msg.text}
                      </Box>
                    </Box>
                  ))}
                </Box>
              </Box>

              <Box sx={{ py: 2, px: 2 }}>
                <Box sx={{ maxWidth: 800, mx: "auto" }}>
                  <ChatInput onSend={handleSend} />
                </Box>
              </Box>
            </>
          )}
        </Box>
      </Box>
    </ThemeProvider>
  );
}

export default App;